package com.example.demo.mock;

import com.example.demo.post.domain.Post;
import com.example.demo.post.service.port.PostRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakePostRepository implements PostRepository {
    private final List<Post> data = new ArrayList<>();
    private Long autoGeneratedId = 0L;

    @Override
    public Optional<Post> findById(long id) {
        return data.stream().filter(it -> it.getId().equals(id)).findAny();
    }

    @Override
    public Post save(Post post) {
        if (post.getId() == null || post.getId() == 0) {
            Post newPost = Post.builder()
                .id(++autoGeneratedId)
                .content(post.getContent())
                .createdAt(post.getCreatedAt())
                .modifiedAt(post.getModifiedAt())
                .writer(post.getWriter())
                .build();
            data.add(newPost);
            return newPost;
        } else {
            data.removeIf(it -> it.getId().equals(post.getId()));
            data.add(post);
            return post;
        }
    }
}
